### ISSUE TITLE
Missing Extension

### ISSUE THREAD

**Issue by weyCC81** [auberginehill/firefox-customization-files#1]
// Extension screenshots
lockPref("extensions.screenshots.disabled", true);
 
// Extension pocket
lockPref("extensions.pocket.enabled", false);

**Comment by auberginehill** [comment]
OK, thanks for the tips!

extensions.pocket.enabled:
https://snakerl.blogspot.com/2017/11/pocket-erweiterung-in-firefox-57.html
-> Added to Optional configuration (firefox.cfg) under the Disable Pocket integration

extensions.screenshots.disabled (requires at least Firefox 55):
https://www.ghacks.net/2017/08/12/how-to-disable-firefoxs-new-screenshot-tool/
-> Added under Optional configuration (firefox.cfg)

Implemented in https://github.com/auberginehill/firefox-customization-files/commit/545a86a3b9483e53b3877fb20e0caa9aa9e93bfa
